gazebo_ros_control:
  pid_gains:
    head_pan: {p: 20.0, i: 0.1, d: 0.0}
    head_tilt: {p: 20.0, i: 0.1, d: 0.0}

head_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - head_pan
    - head_tilt
    
    

